version: '3'
services:
  localhost:
      image: postgres
  migration:
      build: .
    command: python manage.py migrate
    volumes:
        - .:/Users/madina/app
    depends_on: 
      - localhost

  web:
    build: .
    command: py manage.py runserver 127.0.0.1:8000
    volumes: 
        - .:/Users/madina/app
    ports:
        - "8000:8000"
    depends_on: 
        - localhost
        - migration

