version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: *******
    migration:
        build: .
      command: python manage.py migrate
      volumes:
          - .:/app
      depends_on: 
        - db

    web:
      build: .
      command: py manage.py runserver 0.0.0.0:8000
      volumes: 
          - .:/app
      ports:
          - "8000:8000"
      depends_on: 
          - db
          - migration

